url:
baseurl:

# Site settings
title: Mozilla Foundation
email: your-email@domain.com
description: "Information and links from the  Mozilla Open Science Fellows NYC Summit 2019"

# Team names, titles and social links
people:
- name: Kadija Ferryman
  pic: Kadija
  position: Anthropologist
  text: I examine <a href="https://datasociety.net/research/fairness-precision-medicine/">ethics</a>, openness, and <a href="https://cancerletter.com/articles/20181116_1/">inclusion</a> in data-driven precision medicine. 
  social:
    - title: twitter
      url: https://twitter.com/KadijaFerryman
    - title: link
      url: www.kadijaferryman.com

- name: Julia Stewart Lowndes
  pic: Julia
  position: Marine Ecologist & Data Scientist
  text: I build and strengthen communities of practice around environmental open data science. <a href="https://openscapes.org">Openscapes</a> centers around a mentorship program, whose <a href="https://openscapes.org/series">lesson series</a> builds from <a href="https://www.nature.com/articles/s41559-017-0160">Lowndes et al. 2017</a>.
  social:
    - title: twitter
      url: https://twitter.com/juliesquid
    - title: linkedin
      url: https://www.linkedin.com/in/julia-stewart-lowndes
    - title: github
      url: https://github.com/jules32
    - title: link
      url: http://jules32.github.io

- name: Alex Morley
  pic: Alex
  position: Neuroscientist
  text: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut eaque, laboriosam <a href="url">link text</a> veritatis,quos non quis ad perspiciatis, totam corporis ea, alias ut unde.
  social:
    - title: twitter
      url: https://twitter.com/alex__morley
    - title: linkedin
      url: https://www.linkedin.com/in/alexanderjmorley
    - title: github
      url: https://github.com/alexmorley


- name: Ciera Martinez
  pic: Ciera
  position: Evolutionary Biologist
  text: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut eaque, laboriosam <a href="url">link text</a> veritatis,quos non quis ad perspiciatis, totam corporis ea, alias ut unde.
  social:
    - title: twitter
      url: twitter.com/CieraReports
    - title: github
      url: http://github.com/iamciera
    - title: linkedin
      url: https://www.linkedin.com/in/ciera-martinez-phd-b77432120/

- name: Daniela Saderi
  pic: Daniela
  position: Neuroscientist
  text: I am an open science advocate, passionate about research and making scientific output available to everyone to advance knowledge and improve transparency. I recently co-founded <a href=”https://www.prereview.org/”>PREreview</a>, a free online platform to collaboratively write reviews of preprints after discussions at academic journal clubs.
  social:
    - title: twitter
      url: twitter.com/Neurosarda
    - title: github
      url: http://github.com/dasaderi
    - title: linkedin
      url: https://www.linkedin.com/in/daniela-saderi/

- name: Andre Maia Chagas
  pic: Andre
  position: Neuroscientist
  text: I'm interested in pushing open science by building low-cost but high-performance scientific equipment using <a href="https://journals.plos.org/plosbiology/article/metrics?id=10.1371/journal.pbio.3000014">an Open Hardware paradigm</a>. Together with different groups and labs we have been building open science equipment and teaching others to do the same. We are now trying to build a global understanding of current research-tool needs that are not yet being met by competitive open hardware alternatives.
  social:
    - title: twitter
      url: twitter.com/chagas_am
    - title: github
      url: http://github.com/amchagas
    - title: linkedin
      url: https://www.linkedin.com/in/amaiachagas/

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Build settings
markdown: kramdown
permalink: pretty
