url: 
baseurl: 

# Site settings
title: Mozilla Foundation
email: your-email@domain.com
description: "Information and links from the  Mozilla Open Science Fellows NYC Summit 2019"

# Team names, titles and social links
people:
- name: Kadija Ferryman
  pic: Kadija
  position: Anthropologist
  text: I examine <a href="https://datasociety.net/research/fairness-precision-medicine/">ethics</a>, openness, and <a href="https://cancerletter.com/articles/20181116_1/">inclusion</a> in data-driven precision medicine. 
  social:
    - title: twitter
      url: https://twitter.com/KadijaFerryman
    - title: link
      url: www.kadijaferryman.com

- name: Julia Stewart Lowndes
  pic: Julia
  position: Marine Ecologist & Data Scientist
  text: I build and strengthen communities of practice around environmental open data science. <a href="https://openscapes.org">Openscapes</a> engages, empowers, and amplifies scientists, centering around a mentorship program. Its <a href="https://openscapes.org/series">lesson series</a> builds off  <a href="https://www.nature.com/articles/s41559-017-0160">Lowndes et al. 2017</a>.
  social:
    - title: twitter
      url: https://twitter.com/juliesquid
    - title: linkedin
      url: https://www.linkedin.com/in/julia-stewart-lowndes
    - title: github
      url: https://github.com/jules32
    - title: link
      url: http://jules32.github.io

- name: Alex Morley
  pic: Alex
  position: Neuroscientist
  text: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut eaque, laboriosam <a href="url">link text</a> veritatis,quos non quis ad perspiciatis, totam corporis ea, alias ut unde. 
  social:
    - title: twitter
      url: https://twitter.com/alex__morley
    - title: linkedin
      url: https://www.linkedin.com/in/alexanderjmorley
    - title: github
      url: https://github.com/alexmorley
    

- name: Ciera Martinez
  pic: Ciera
  position: Evolutionary Biologist
  social:
    - title: twitter
      url: twitter.com/CieraReports
    - title: github
      url: http://github.com/iamciera
    - title: linkedin
      url: https://www.linkedin.com/in/ciera-martinez-phd-b77432120/

- name: Daniela Saderi
  pic: Daniela
  position: Neuroscientist
  social:
    - title: twitter
      url: twitter.com/Neurosarda
    - title: github
      url: http://github.com/dasaderi
    - title: linkedin
      url: https://www.linkedin.com/in/daniela-saderi/

- name: Andre Maia Chagas
  pic: Andre
  position: Neuroscientist
  social:
    - title: twitter
      url: twitter.com/chagas_am
    - title: github
      url: http://github.com/amchagas
    - title: linkedin
      url: https://www.linkedin.com/in/amaiachagas/

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Build settings
markdown: kramdown
permalink: pretty
